### ISSUE TITLE
where these values(UUID_MILI_SERVICE,UUID_CHAR_pair, etc) are from

### ISSUE THREAD

**Issue by skywalkerlw** [paulgavrikov/xiaomi-miband-android#1]
Is there any original document that defines UUID_MILI_SERVICE,UUID_CHAR_pair, etc values?

**Comment by Andychoi153** [comment]
If you  decompile mi band app that from android, you can view the source
code of mi band and uuid code. If you want that application, I will give
you.
2015. 5. 17. 오전 7:12에 "Liang Wang" notifications@github.com님이 작성:

**Comment by paulgavrikov** [comment]
There is no official doc, xiaomi - and I would bet on this - will never release one. Everything is taken from the source.
